require: rubocop-rails

AllCops:

  Exclude:

    - spec/support/spec_helper.rb

    - spec/rails_helper.rb

    - app/helpers/devise_helper.rb

Documentation:

  Enabled: false

LineLength:

  Max: 99

Style/FrozenStringLiteralComment:

  Enabled: false

Metrics/BlockLength:

  Exclude:

    - spec//*

    - app/admin//*